openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Service Color

paths:
  /v4/color/checker:
    get:
      summary: Route to check if the service is up.
      operationId: checker
      tags:
        - checker
      responses:
        "200":
          description: Returning OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Always true for 200 response
                  message:
                    type: string
                example:
                  success: true
                  message: "OK"
        "500":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  success: false
                  error:
                    code: 500
                    message: "An internal error occured"

  /v4/color/{r},{g},{b}/{filename}:
    get:
      summary: Colorized the specified symbol with the specified color.
      operationId: color
      tags:
        - color
      parameters:
        - in: path
          name: r
          schema:
            type: integer
          required: true
          description: The value of the red color channel
        - in: path
          name: g
          schema:
            type: integer
          required: true
          description: The value of the greeb color channel
        - in: path
          name: b
          schema:
            type: integer
          required: true
          description: The value of the blue color channel
        - in: path
          name: filename
          schema:
            type: string
          required: true
          description: Filename of the symbol to be colorized
      responses:
        "200":
          description: Returns the symbol colorized in the specified colors.
          content:
            image/png:
              schema:
                type: string
                format: binary

        "400":
          description: Bad Requests. This can be caused by ill defined parameters, or the host/the domain is/are not part of the authorised hosts/domains.
          content:
            text/html:
              schema:
                type: string
                example: "Color channel values must be integers in the range of 0 to 255."

        "500":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  success: false
                  error:
                    code: 500
                    message: "An internal error occured in service color."

components:
  schemas:
    error:
      type: object
      properties:
        success:
          type: boolean
          description: Always false in case of error
        error:
          type: object
          properties:
            code:
              type: integer
              description: Error code
            message:
              type: string
              description: Description of the error
